// Generated by Wrangler by running `wrangler types`

interface Env {
	WEBFLOW_CLIENT_ID: string;
	WEBFLOW_CLIENT_SECRET: string;
	REDIRECT_URL: string;
	PORT: string;
	VITE_PORT: string;
	JWT_SECRET: string;
	DB: D1Database;
}
