// Generated by Wrangler by running `wrangler types`

interface Env {
	WEBFLOW_CLIENT_ID: "516ad6cc9cb1d3b4a1780e18aaa8feed7ae4285d9db0ff8e480576cf969e6c00";
	REDIRECT_URL: "https://epyc-slider-api.epyc.us/auth";
	WEBFLOW_CLIENT_SECRET: string;
	JWT_SECRET: string;
	DB: D1Database;
}
