name = "epyc-webflow-slider-app-backend"
main = "src/index.ts"
compatibility_date = "2024-11-27"

[[d1_databases]]
binding = "DB"
database_name = "epyc-slider-app-db"
migrations_table = "d1_migrations"
database_id = "8a8a6a64-61b5-4ab9-97f3-8f1eeb481061"
migrations_dir = "migrations"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
WEBFLOW_CLIENT_ID = "516ad6cc9cb1d3b4a1780e18aaa8feed7ae4285d9db0ff8e480576cf969e6c00"
REDIRECT_URL = "https://epyc-slider-api.epyc.us/auth"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
# head_sampling_rate = 1
